# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f76b2f25803d5da1e29f6d8ff619cc5c15a4ce965aa5f39c563816727656f2fc71ae5729c17cfb2a1f930ce8601d9f4aeb1377ec3d00d90cfae78b532745a056

test:
  secret_key_base: 903691f8512d9f7e5c6873f448e3dd787f4d17ca27527d9d2d2c216e3e0a21e48a668f68f6d4beedde1e1c1dcc3d6b16b24278d80ffbf6f5c7e396c6f71db4f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
